language: python

python:
  - 2.7
  - 3.4
  - pypy
  - pypy3

install:
  - pip install coveralls

script:
  - python setup.py install
  - coverage run --include=*spotipy* tests/tests.py
  - for file in examples/*.py; do echo "Running" $file; python $file; done

after_success:
  - coverage report
  - coveralls
  - pip install pep8 pyflakes
  - pep8 *.py tests/*.py
  - pyflakes *.py tests/*.py

matrix:
  allow_failures:
    - python: 3.4
    - python: pypy3
